name: "⚒️ REFACTOR"
description: "코드의 구조와 품질을 개선하기 위한 작업입니다. 기존 기능의 동작은 유지하되 코드 유지보수성과 성능을 향상시킵니다."
labels: [refactor]
title: "[REFACTOR] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요"
      placeholder: "GH-1234"
    validations:
      required: true

  - type: input
    id: refactorTask
    attributes:
      label: "체크리스트(Tasks)"
      description: "수정할 코드 범위 또는 파일의 작업목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: textarea
    id: refactorReason
    attributes:
      label: "리팩토링 이유"
      description: "리팩토링이 필요한 이유와 기대하는 결과를 설명해주세요"
    validations:
      required: true
