name: "✅ UPDATE"
description: "기존 기능을 개선하거나 성능을 향상시키는 작업입니다. 사용자 경험을 개선하거나 시스템 효율성을 높이기 위한 업데이트를 수행합니다."
labels: [update]
title: "[UPDATE] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요"
      placeholder: "GH-1234"
    validations:
      required: true

  - type: input
    id: featureToUpdate
    attributes:
      label: "개선할 기능"
      description: "수정 또는 개선할 주요 기능을 입력해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: textarea
    id: improvementSummary
    attributes:
      label: "개선 사항"
      description: "변경할 주요 내용과 기대 결과를 간략히 설명해주세요"
    validations:
      required: true
