name: "✨ FEATURE"
description: "새로운 기능을 추가하고 시스템을 확장하기 위한 작업입니다. 프로젝트 요구 사항에 맞는 주요 기능을 설계하고 개발합니다."
labels: [feature]
title: "[FEATURE] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요"
      placeholder: "GH-1234"
    validations:
      required: true

  - type: input
    id: featureName
    attributes:
      label: "기능 이름"
      description: "추가할 새로운 기능의 이름을 입력해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: textarea
    id: featureDescription
    attributes:
      label: "기능 설명"
      description: "기능의 주요 동작과 기대 결과를 설명해주세요"
    validations:
      required: true
