name: Create Jira issue
on:
  issues:
    types:
      - opened
jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser - Refactor
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-refactor
        with:
          template-path: .github/ISSUE_TEMPLATE/refactor.yml

      - name: Issue Parser - Update
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-update
        with:
          template-path: .github/ISSUE_TEMPLATE/update.yml

      - name: Issue Parser - Style
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-style
        with:
          template-path: .github/ISSUE_TEMPLATE/style.yml

      - name: Issue Parser - Bug
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-bug
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yml

      - name: Issue Parser - Feature
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-feature
        with:
          template-path: .github/ISSUE_TEMPLATE/feature.yml

      - name: Issue Parser - Del
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-del
        with:
          template-path: .github/ISSUE_TEMPLATE/del.yml

      - name: Issue Parser - Fix
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser-fix
        with:
          template-path: .github/ISSUE_TEMPLATE/fix.yml

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.issueparser_parentKey }}'
          echo '${{ steps.issue-parser.outputs.__ticket_number }}'
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: GH
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
              }
            }

      - name: Log created issue
        run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"

      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.create.outputs.issue }}"
          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser_branch}}"
          BRANCH_NAME="${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[${{ steps.create.outputs.issue }}] ${{ github.event.issue.title }}"

      - name: Add comment with Jira issue link
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: "Jira Issue Created: [${{ steps.create.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create.outputs.issue }})"
